#! /usr/bin/env bash

help () {
    cat << EOF

Usage: make [options]

Options:

    verify          Make the codebase adhere to the rules
    is_verified     Check if the codebase adhere to the rules

EOF

}

verify () {
    echo "::: Format with black"
    black src/

    echo "::: Lint with pylint"
    pylint src/

    echo "::: Is all test passed"
    pytest src/

    echo "::: Is all lines covered"
    coverage run -m pytest src/
    coverage report -m

}

is_verified () {
    echo "::: Is formatted with black"
    black --check src/

    echo "::: Is linted with pylint"
    pylint src/

    echo "::: Is all test passed"
    pytest src/

}



if [ ! -n "$1" ]
then
    help
    exit
fi

while [ -n "$1" ]; do

    case "$1" in

        verify) verify ;;
        is_verified) is_verified ;;
        help) help ;;

    esac
    break

done

